//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises
    {
        public int ID { get; set; }
        public string CodigoISO { get; set; }
        public int CodigoPais { get; set; }
        public string Nome { get; set; }
        public string URLBandeira { get; set; }
    }
}
