//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposProgramaMobilidade
    {
        public int ID { get; set; }
        public string Descricao { get; set; }
        public string Designacao { get; set; }
        public string URLImagem { get; set; }
    }
}
